feat(mesh): Add mesh config and others
Kiesen/graphql-mesh-express pull request #3
Opened 2021-03-03 15:52 UTC by angelsvirkov

- Add `graphql-tag` package
- Add mesh config
- Add additional type defs / resolvers
- Add user rights
- Add custom fetch
- Add `getUserRights` middleware

2021-03-04 13:38 UTC, Kiesen requested changes
Looks good to me, I just found some minor things and recommendations.

2021-03-04 13:38 UTC, Kiesen commented on packages/backend/src/config/Endpoints.ts
> +  // TODO: Find a Public GQL Service which can be used in two environments way
I think finding a public GQL service with two environments is hard to find. Maybe we can just use one service but within two input handlers? 

This one: https://graphqlzero.almansi.me/ looks promising to me.

2021-03-04 13:38 UTC, Kiesen commented on packages/backend/src/mesh/mesh.ts
> +import { additionalResolvers } from './additionalResolvers/additionalResolvers';
```suggestion
import { additionalResolvers } from '@src/mesh/additionalResolvers/additionalResolvers';
```

2021-03-04 13:38 UTC, Kiesen commented on packages/backend/src/mesh/mesh.ts
> +import { additionalTypeDefs } from './additionalTypeDefs';
```suggestion
import { additionalTypeDefs } from '@src/mesh/additionalTypeDefs';
```

2021-03-04 13:38 UTC, Kiesen commented on packages/backend/tsconfig.json
> +      "@_types/*": ["src/_types/*"],
Just a minor but I would like to put the types under `types`

```suggestion
      "@types/*": ["src/types/*"],
```

2021-03-04 15:43 UTC, angelsvirkov commented on packages/backend/tsconfig.json
> +      "@_types/*": ["src/_types/*"],
As agreed , we change it to
`@internalTypes/*: ["src/types/*]`

2021-03-05 07:42 UTC, angelsvirkov commented on packages/backend/tsconfig.json
> +      "@_types/*": ["src/_types/*"],
Done

2021-03-08 11:28 UTC, Kiesen requested changes
Found three minors - after committing them the PR can get merged.

2021-03-08 11:28 UTC, Kiesen commented on packages/backend/src/app.ts
> +import { getUserRights } from './middleware/getUserRights';
Found a minor:

```suggestion
import { getUserRights } from '@src/middleware/getUserRights';
```

2021-03-08 11:28 UTC, Kiesen commented on packages/backend/src/rights/rights.ts
> +import { MutationConfig } from './config';
Minor:

```suggestion
import { MutationConfig } from '@src/rights/config';
```

2021-03-08 11:28 UTC, Kiesen commented on packages/backend/src/rights/rights.ts
> + * allow/deny mutations based on a user rights. This is configured via resolvers specifying
Another minor:

```suggestion
 * allow/deny mutations based on user rights. This is configured via resolvers specifying
```

2021-03-08 11:41 UTC, Kiesen approved these changes
Looks good to me. 👍

2021-03-08 11:41 UTC, merged