Feature/add features to mesh
Kiesen/graphql-mesh-express pull request #5
Opened 2021-03-09 11:07 UTC by angelsvirkov

It might be useful to look at the commit messages to see what has features have been added

2021-03-09 19:19 UTC, Kiesen requested changes
Overall everything looks good to me. Added just two minor remarks. Also I would suggest to rename all manager related things maybe to something more generic, maybe `user` or `moderator`.

2021-03-09 19:19 UTC, Kiesen commented on packages/backend/package.json
> +    "graphql-voyager": "^1.0.0-rc.31",
Isn't this more like a dev dependency? I know in our case it doesn't matter but in a real environment you would place it to the dev dependencies or?

2021-03-09 19:19 UTC, Kiesen commented on packages/backend/src/mesh/additionalResolvers/typeResolvers/additionalManagerInfo.ts
> +  address: () => 'Kesselstrasse 5 - 7, 40221 Dusseldorf Germany',
Maybe we can use faker.js here to generate a random address.

2021-03-10 08:37 UTC, angelsvirkov commented on packages/backend/package.json
> +    "graphql-voyager": "^1.0.0-rc.31",
It is not a dev dependency because I have exposed it on the express server without a conditional check. Also we don't really have `process.env` set up anyway

2021-03-10 08:38 UTC, angelsvirkov commented on packages/backend/src/mesh/additionalResolvers/typeResolvers/additionalManagerInfo.ts
> +  address: () => 'Kesselstrasse 5 - 7, 40221 Dusseldorf Germany',
I don't see this address as a problem because it is public anyway but I will add another static address (without using faker.js because it is not a dependency in the `backend` and I think it is not needed for now)

2021-03-10 16:39 UTC, Kiesen approved these changes

2021-03-10 16:39 UTC, merged